# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do

	# You still need to update version & build number (App + Widget) + create new version in app store
	desc "Upload a new version on app store (and take screenshots) 🥳"
	lane :screenshots_and_deploy do
		take_screenshots
		private_deploy(skip_screenshots: false)
	end

	desc "Upload a new version on app store (and dont take screenshots) 🥳"
	lane :deploy do
		private_deploy(skip_screenshots: true)
	end

	desc "Take screenshots 📸"
	private_lane :take_screenshots do
		devices = ["iPhone 8 Plus", "iPhone 12 Pro Max", "iPad Pro (12.9-inch) (3rd generation)", "iPad Pro (12.9-inch) (3rd generation)", "iPad Pro (12.9-inch) (2nd generation)"]
		languages = ["en-US", "fr-FR"]
		scheme = "SimpleWeather"

		capture_ios_screenshots(
			scheme: scheme,
			devices: devices,
			languages: languages,
			output_directory: "./fastlane/screenshots",
			override_status_bar: true,
			dark_mode: true,
			clear_previous_screenshots: true,
			skip_open_summary: true
		)
	end

	private_lane :private_deploy do |options|
		scheme = "SimpleWeather"
		skip_screenshots = options[:skip_screenshots]

		build_app(
			scheme: scheme,
			include_bitcode: true,
			output_directory: "./fastlane/build"
		)

		upload_to_app_store(
			force: true,
			metadata_path: "./fastlane/metadata",
			screenshots_path: "./fastlane/screenshots",
			ipa: "./fastlane/build/SimpleWeather.ipa",
			overwrite_screenshots: true,
			submit_for_review: true,
			automatic_release: true,
			username: "maxime.maheo@gmail.com",
			submission_information: {
				add_id_info_uses_idfa: false
			},
			skip_screenshots: skip_screenshots
		)

		upload_symbols_to_crashlytics(
			dsym_path: "./fastlane/build/SimpleWeather.app.dSYM.zip"
		)
	end

end